//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace html2apk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("html2apk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;activity android:label=&quot;@string/app_name&quot; android:screenOrientation=&quot;{orientation}&quot; android:name=&quot;.MainActivity&quot; android:theme=&quot;@android:style/Theme.NoTitleBar&quot;&gt;
        ///		&lt;intent-filter&gt;
        ///			&lt;action android:name=&quot;android.intent.action.MAIN&quot; /&gt;
        ///			&lt;category android:name=&quot;android.intent.category.LAUNCHER&quot; /&gt;
        ///		&lt;/intent-filter&gt;
        ///	&lt;/activity&gt;.
        /// </summary>
        internal static string MainActivity {
            get {
                return ResourceManager.GetString("MainActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;activity android:alwaysRetainTaskState=&quot;true&quot; android:clearTaskOnLaunch=&quot;true&quot; android:configChanges=&quot;keyboardHidden&quot; android:label=&quot;@string/app_name&quot; android:launchMode=&quot;singleTop&quot; android:name=&quot;.SplashScreen&quot; android:noHistory=&quot;true&quot; android:screenOrientation=&quot;{orientation}&quot; android:theme=&quot;@android:style/Theme.NoTitleBar&quot;&gt;
        ///            &lt;intent-filter&gt;
        ///                &lt;action android:name=&quot;android.intent.action.MAIN&quot;/&gt;
        ///                &lt;category android:name=&quot;android.intent.category.LAUNCHER&quot;/&gt;
        ///         [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Splashscreen {
            get {
                return ResourceManager.GetString("Splashscreen", resourceCulture);
            }
        }
    }
}
